
# ********** SERVICES *************************
# ------------------------------------------------
#      SERVICE              |       ADDRESS
# ----------------------------------------------
#    rate limiter server                 localhost:9100               


services:
        
  # Rate Limiter 
  rate-limiter:
    build: .
    ports:
      - "9100:9100" # Make sure the container port (so the java server) is the same as SERVER_PORT in this file
    environment:
      SPRING_PROFILES_ACTIVE: local # Spring "local" profile, and all its properties, will be used
      SERVER_PORT: 9100 # This is the port of the java server. It overrides the port defined in "local" profile
    
